version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - FRONTEND_URL=http://frontend:3000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      REACT_APP_BACKEND_URL: "http://backend:4000"
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
