apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.frontend.image.repository }}:{{ .Values.frontend.frontend.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.frontend.frontend.image.imagePullPolicy }}
        env:
        - name: REACT_APP_BACKEND_URL
          value: {{ quote .Values.frontend.frontend.env.reactAppBackendUrl }}
        ports:
        - containerPort: 3000
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: {{ .Values.frontend.type }}